### ISSUE TITLE
Hooks call stack broken on Chromium based browsers

### ISSUE THREAD

**Issue by alloy** [lahmatiy/react-render-tracker#22]
I’m on macOS 12.0.1 (x86_64) and am using [this example app](https://github.com/microsoft/graphitation/tree/apollo-fragment-store-watching/examples/apollo-watch-fragments).

I have tested this on:

* MS Edge 96.0.1054.62 (Official build) (x86_64)
* Chromium 85.0.4183.102 (Developer Build) (64-bit)

It _does_, however, work correctly with Firefox.

<img width="2560" alt="Screenshot 2022-01-05 at 13 04 42" src="https://user-images.githubusercontent.com/2320/148215244-16ba4c3f-9d1f-4543-a3ba-42aecd2b789f.png">

**Comment by lahmatiy** [comment]
The problem arises because the example uses RRT in conjunction with WhyDidYouRender, which patches hook functions, thereby adding an additional entry to the stack trace. Furthermore, SpiderMonkey (Firefox) and V8 generate stack traces differently, which resulted in the WhyDidYouRender wrapper over the hook not being included in the path in Firefox. Path construction in RRT was based on the assumption that all function names in the path should start with "use", which is not always the case. I have revamped this functionality so as not to rely on function names. Now, paths are generated consistently across all browsers.

Chrome:

<img width="700" alt="image" src="https://github.com/lahmatiy/react-render-tracker/assets/270491/cda72560-a6d4-44e1-9b48-7166a2c86245">

Firefox:

<img width="662" alt="image" src="https://github.com/lahmatiy/react-render-tracker/assets/270491/7924a53f-bd99-448d-afd2-2ebeb7f73a13">

You may notice the difference in paths across browsers in a "hook" name before "useState". That's a WDYR wrapper over the React's hook. WDYR tries to [set a name for the wrapper function](https://github.com/welldone-software/why-did-you-render/blob/0f364e8451f5283e4d59054c96a9e2788f497045/src/whyDidYouRender.js#L202) which works for SpiderMonkey but ignored by V8.

Also you may notice a component name in the beginning of a path. That's because of WDYR wraps component functions as well. If you disable WDYR then a path will be shorter by 2 entries and consistent across browsers:

<img width="699" alt="image" src="https://github.com/lahmatiy/react-render-tracker/assets/270491/4b1a4282-5ad7-419d-9596-e4ec6223d096">

Fixes will be available in next release of RRT.
