### ISSUE TITLE
Rempl in devtools is not working anymore

### ISSUE THREAD

**Issue by MikeYermolayev** [lahmatiy/react-render-tracker#26]
I used to use react-render-tracker with rempl but seems liie it's not working anymore. All I get in devtools is a white screen
<img width="875" alt="image" src="https://user-images.githubusercontent.com/8783498/177302909-6989f8e0-9ee4-4414-9af8-84728d178814.png">

Meanwhile inpage cconfig works ok
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/8783498/177303153-28a60510-5299-4c96-8aff-7f84f30f0223.png">

React: 16.14
Browser: Brave [Version 1.40.107 Chromium: 103.0.5060.53 (Official Build) (x86_64)](https://brave.com/latest/)
Rempl: 1.0.3

**Comment by lahmatiy** [comment]
Thank you for the report. We aware of the issue, this is a consequence of disabling CSP settings in Rempl devtools extension at the request of the store and incorrect testing after changes on our side. I have been looking for a solution for the last two days (make it works without enabling too relaxing CSP settings that have been compromised) and luckily found it. It remains to conduct the last testing and publish rempl, its devtools extension and React Render Tracker as well. The issue will be fixed in the coming days.

**Comment by lahmatiy** [comment]
Just published a new version of RRT [0.7.0](https://github.com/lahmatiy/react-render-tracker/releases/tag/v0.7.0). This release doesn't fix the issue, but it should works with new version [1.0.4](https://github.com/rempl/rempl-browser-extension/releases/tag/v1.0.4) of Rempl extension. The extension already available in [Mozilla Browsers add-ons](https://addons.mozilla.org/en-US/firefox/addon/rempl/), but on review in [Chrome web store](https://chrome.google.com/webstore/detail/rempl/hcikjlholajopgbgfmmlbmifdfbkijdj). Until the extension is not updated in Chrome web store, you can load it from [an archive in release notes](https://github.com/rempl/rempl-browser-extension/releases/tag/v1.0.4) (see instruction [here](https://github.com/rempl/rempl-browser-extension#development))

**Comment by lahmatiy** [comment]
Rempl extension in Chrome web store was updated yesterday. Everything works as expected now. Just make sure you are using latest versions of RRT & rempl extension.
