### ISSUE TITLE
Connection to rempl publisher – pending

### ISSUE THREAD

**Issue by nickshevr** [lahmatiy/react-render-tracker#7]
I used local overridesin Chrome  to create `script` tag in html.

```
<script src="https://unpkg.com/react-render-tracker"></script>
```

My `react` script is `defer`, so I think it would start later. Also I don't have issues with csp.

And I got next status checks:
```
Connection to page – OK
Connection to rempl – OK
Connection to rempl publisher – pending...
NOTE: Page should contains a rempl publisher
``` 

What is `rempl publisher`? And how can I check that order of React -> RRT is right? There are no errors/warnings/etc in console.

**Comment by nickshevr** [comment]
![image](https://user-images.githubusercontent.com/16756393/130647090-29772c14-8bff-4eae-a283-85d871f275af.png)
Script is executing in right way.

**Comment by lahmatiy** [comment]
Publisher is a part of the tool that is integrating with React and send data to UI. React render tracker (RRT) is built on Rempl which provides UI host init and transport layer. In your case publisher didn't connect to Rempl endpoint. This might be because of RRT script is not executed or executed in a sandbox or another frame. But to make sure I need to repro your scenario.

**Comment by Tom910** [comment]
@lahmatiy 
1) visit https://avito.ru (that site don't have CSP)
2) run in console - `const scriptElement = document.createElement('script'); scriptElement.src='https://unpkg.com/react-render-tracker'; document.querySelector('body').append(scriptElement)`
3) open rempl tab

**Comment by lahmatiy** [comment]
@Tom910 This will not work because the script must execute before the React is initialized. React is checking `__REACT_DEVTOOLS_GLOBAL_HOOK__` in global to attach to a tool. So if React executes first it will not be connected to a tool.

**Comment by nickshevr** [comment]
@lahmatiy think we need an error in console for this case, if it is possible.
I did these things:
- add `setTimeout` to react script (local override), also it had `defer` option
- add to another `async` script creating `unpkg/rrt` as a sync script

I checked with debugger, `react` initializing started after `rrt` executed.

**Comment by nickshevr** [comment]
Ok, I have two react on site, kek
So the real issue was created by order execution.

And wan't to copypaste that.
```
Think we need an error in console for this case, if it is possible.
```

**Comment by lahmatiy** [comment]
@nickshevr So problem is still here or not? :)
It not clear to me how do you use overrides. I tried Tampermonkey to inject a script (`document.createElement('script')` etc) and got the same issue. Then I copy&pasted source of RRT from cdn, the problem is gone. However for avito.ru it shows nothing 🤔 For a couple of other sites using React it works fine

**Comment by christopher-caldwell** [comment]
> @Tom910 This will not work because the script must execute before the React is initialized. React is checking `__REACT_DEVTOOLS_GLOBAL_HOOK__` in global to attach to a tool. So if React executes first it will not be connected to a tool.

Does this mean this tool automatically doesn't run if the dev tools aren't bundled? Namely if your build the app meant for a production environment. In case my question was unclear, does this run when using the production build of react?
